### ISSUE TITLE
Usable in Column

### ISSUE THREAD

**Issue by niallmurphy-ie** [otacke/h5p-agamotto#14]
Beautiful contribution to h5p. Are there any plans to incorporate this into Column? Would be nice to add questions etc. underneath agamotto.

Thanks

**Comment by otacke** [comment]
I didn't have plans so far, but I will look into it.

**Comment by niallmurphy-ie** [comment]
Thanks!

**Comment by niallmurphy-ie** [comment]
Agamotto actually works fine once added to the list of field option is Column's semantics.json. I don't know if they will automatically add it or perhaps you can request it. I think the width of it just needs to be widened a bit inside the column.

![agamotto](https://user-images.githubusercontent.com/12254043/27032700-6c64359e-4fa0-11e7-8ca5-23ce3721fdef.png)


Either way, I'm going to start using it today. Thanks again for the great contribution. I

**Comment by otacke** [comment]
I thought it was as easy as that, see my post [https://h5p.org/node/87693](https://h5p.org/node/87693) from this morning :-)

**Comment by niallmurphy-ie** [comment]
Yeah I only realised today that for changes in the json files to be applied in Drupal, you need to "upgrade" the content type. I wish I knew that ages ago.

Btw, I can't access that link.

**Comment by niallmurphy-ie** [comment]
Hi otacke, I realised there that in a column in Firefox, there is a constant re-firing of your resize function  starting on line 188 of agamotto.js. I think it only happens when other content is also added and it kills page functionality (but is a good Windows 95 emulator I guess). Edge and Chrome test fine for me.

```
// Add Resize Handler
      window.addEventListener('resize', function (e) {
        /*
         * Decrease the size of the content if on a mobile device in landscape
         * orientation, because it might be hard to use it otherwise.
         * iOS devices don't switch screen.height and screen.width on rotation
         */
        if (isMobileDevice() && Math.abs(window.orientation) === 90) {
          if (/iPhone/.test(navigator.userAgent)) {
            that.wrapper.style.width = Math.round((screen.width / 2) * that.images.getRatio()) + 'px';
          }
          else {
            that.wrapper.style.width = Math.round((screen.height / 2) * that.images.getRatio()) + 'px';
          }
        }
        else {
          // Portrait orientation
          that.wrapper.style.width = 'auto';
        }

        that.images.resize();
        that.slider.resize();
        // The descriptions will get a scroll bar via CSS if neccesary, no resize needed

        // Resize iframe if image's height is too small or too high.
        var windowHeight = window.innerHeight;
        var wrapperHeight = that.wrapper.offsetHeight;
        var actionBar = document.querySelector('.h5p-actions');
        var actionBarHeight = actionBar ? actionBar.offsetHeight : -1;
        if (wrapperHeight + actionBarHeight + 1 !== windowHeight) {
          that.trigger('resize');
        }
      });

```
Removing the contents of that function gets rid of the re-firing but breaks the resizing of content on screen size change.

I wonder if there is some check you can add to combat it?

Thanks,
Niall

**Comment by otacke** [comment]
Thanks! Will look into it.

**Comment by otacke** [comment]
I changed the resize handling. You can use the latest version from this repository with _H5P.Column_ now. Just let me know if it works for you now.
