### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by otacke** [otacke/h5p-agamotto#27]
See https://h5p.org/node/152958 for request.

**Comment by sevesach** [comment]
I realize this is an old request, but I'd also like to see the ability to expand Agamotto image blender activities to full screen view. :)

**Comment by otacke** [comment]
Features work themselves out, given time ;-)

**Comment by keremnymn** [comment]
This hasn't been implemented?

**Comment by otacke** [comment]
@keremnymn Obviously.

**Comment by otacke** [comment]
@sevesach @keremnymn There you go: https://github.com/otacke/h5p-agamotto/releases/tag/1.6.0 No, I unfortunately don't know when the H5P core team will find some time to release the update.
