### ISSUE TITLE
Bug with Audio

### ISSUE THREAD

**Issue by rezeau** [otacke/h5p-agamotto#325]
Using h5p-agamotto latest version 1.6.3 in an interactive book. If an audio element is added to an image description, then the audio plays automatically when navigating to the page just before the agamotto content!
Steps to reproduce (on a dev site)
1.- Have latest h5p-agamotto version 1.6 installed on your dev site
2.- h5p-column create a new branch, e.g. testing_audio and, in semantics, change "H5P.Agamotto 1.5" to "H5P.Agamotto 1.6"
3.- Create an H5P Interactive Book
4.- Create page 1 with only a Text content in it
5.- Create page 2 with a Multiple Choice question in it
6.- Create page 3 with an Agamotto content in it with 3 images with an Audio component for each.
7.- Save and run the H5P Interactive Book
8.- Page 1 : read the text
9.- Navigate to page 2 (with the MCQ question) : the Audio content of the last image in your Agamotto content (on page 3) is automatically started!
10.- If you continue to navigate, to the end of the IB, then check the Restart button, navigating to page 2 does not play the agamotto Audio... When you arrive on page 3, the Audio player button is in the ON state but nothing plays... You have to click it to OFF, then to ON again for the audio to play.

**Comment by otacke** [comment]
That happens because a Column chapter is preloaded and instantiated by Interactive Book before it is shown.

**Comment by otacke** [comment]
Fixed in https://github.com/otacke/h5p-agamotto/commit/d8fbe8710097cad194f9488aa35e5a358361b860

**Comment by rezeau** [comment]
Thanks for the super-fast fix, Oliver!

**Comment by otacke** [comment]
@rezeau No problem. I'd need to check all my content types that play media themselves for the same issue anyway (and apply the same fix). They should not play audio if they are not visible. JigsawPuzzle, Advent Calendar, Crossword ...
