### ISSUE TITLE
Leaving 'Description Text' blank returns error 

### ISSUE THREAD

**Issue by dannylonglegs** [otacke/h5p-agamotto#39]
When the description text is left blank, the user receives, "Uncaught TypeError: Cannot read property 'getCurrentDescriptionText' of undefined". This leads to display issues.

![h5p-agamatto issue](https://user-images.githubusercontent.com/21149722/59282286-a839e580-8c36-11e9-9eb3-09f26d450832.JPG)

**Comment by otacke** [comment]
@dannylonglegs [Fixed.](https://github.com/otacke/h5p-agamotto/commit/af4dceb0f1ffcad1d80bc4b226d4c5a5de30d8ec) Thanks!
