### ISSUE TITLE
Allow HTML tags MARK and ABBR be used in image descriptions.

### ISSUE THREAD

**Issue by dosse** [otacke/h5p-agamotto#390]
Hello Oliver,
I'm using your great feature for the setup of a training course, and would need a few specific features useful in this context.

Would it please be possible to allow for additional HTML [tags in Agamotto image descriptions](https://github.com/otacke/h5p-agamotto/blob/a543b4435709929afa785a196b099632615e5095/semantics.json#L60)? I would need the tags `mark` to highlight words (e.g. `<mark>highlighted text</mark>`) and `abbr/title` to add a tooltip (e.g. `<abbr title="tooltip text">text with tooltip</abbr>`).

While I can currently copy/paste such formatted text into the description edit field:  
![image](https://user-images.githubusercontent.com/1862608/215093289-4ad33e60-d5e0-4eaf-9146-aa6f27fada4e.png)

once it is saved and displayed the formatting currently gets lost:  
![image](https://user-images.githubusercontent.com/1862608/215093526-7e85661a-e358-470a-b59b-fe3e0a6d8943.png)

Or maybe you could point me please to alternative approaches to achieve this?
Thanks in advance for your help.

**Comment by otacke** [comment]
@dosse Sorry, that's something out of the control of H5P content types. There's a limited set of HTML tags that H5P core allows in text fields. It filters out anything that's not allowed, that's why your copy&paste approach doesn't work.
