### ISSUE TITLE
[question] How to hide title?

### ISSUE THREAD

**Issue by softmonaut** [otacke/h5p-agamotto#440]
How can the title above the images be hidden or not displayed at all like in this [Example](https://h5p.org/content-types/agamotto#example=79243)
Tested with 1.5.2 and 1.6.4 in Moodle 3.11.16. Title is constrained to be not empty (Editor) and an empty Headings field will cause the title to be displayed(?). In short: Something always seems to be displayed. I would be grateful if you could shed some light on this. Maybe it's intended to be not empty, that's ok for me. I just want to make sure I didn't miss anything.

Thanks and greetings
Jörg

**Comment by otacke** [comment]
There's a `Title` field in the editor which is created by H5P core, and that one is mandatory. It's not relevant here though.

There's the `Heading` field in the editor which is part of Agamotto and which is optional. If nothing is set there, then no heading should be displayed: https://github.com/otacke/h5p-agamotto/blob/master/src/scripts/h5p-agamotto.js#L276-L282

**Comment by otacke** [comment]
@softmonaut Cleaning up. I have not received any answer, so I am going to close this issue. Please create a new one if you think something is wrong.
