### ISSUE TITLE
Agamatto doesn't work with Internet Explorer 11

### ISSUE THREAD

**Issue by Urpokarhu1** [otacke/h5p-agamotto#49]
Hello,

mod_hvp 1.20, Agamatto Agamotto (1.4.3) doesn't work at all with Internet Explorer 11, it just displays blank picture. Here is attached the example h5p used.

![aga1](https://user-images.githubusercontent.com/53904029/68197952-d3e1b180-ffc3-11e9-99d0-5cc44d602b16.png)

![aga2](https://user-images.githubusercontent.com/53904029/68197960-d7753880-ffc3-11e9-9f8b-0ae132716151.png)

[jarin-agamatto-5-11-2019-478.zip](https://github.com/otacke/h5p-agamotto/files/3808337/jarin-agamatto-5-11-2019-478.zip)

**Comment by thomasmars** [comment]
Hi,
Please check your browser's console for errors.

**Comment by thomasmars** [comment]
and please post this in the agamotto repository, I'm sure Oliver will fix it as soon as he is able to: https://github.com/otacke/h5p-agamotto

**Comment by Urpokarhu1** [comment]
Hello,

This is what console has to say. Older Agamatto example from h5p.org doesn't work but newer one does with IE11.

![console](https://user-images.githubusercontent.com/53904029/68198625-10fa7380-ffc5-11e9-967d-bc5e81d660d7.PNG)

[older.zip](https://github.com/otacke/h5p-agamotto/files/3808371/older.zip)

[newer.zip](https://github.com/otacke/h5p-agamotto/files/3808372/newer.zip)

**Comment by Urpokarhu1** [comment]
Error in text:

`DOM7011: Tällä sivulla oleva koodi esti välimuistin käytön eteen- ja taaksepäin selauksessa. Lisätietoja on osoitteessa http://go.microsoft.com/fwlink/?LinkID=291337
view.php

HTML1300: Navigointitapahtuma.
view.php

DOM7011: Tällä sivulla oleva koodi esti välimuistin käytön eteen- ja taaksepäin selauksessa. Lisätietoja on osoitteessa http://go.microsoft.com/fwlink/?LinkID=291337
view.php

HTML1512: Vastineeton lopputunniste.
view.php (87,471)
moodle-core-event: Global event published: FORM_ERROR
moodle-core-event: Global event published: BLOCK_CONTENT_UPDATED
Possible Unhandled Promise Rejection: TypeError: Määrittämättömän tai tyhjän viittauksen ominaisuutta textContent ei voi noutaa
   "Possible Unhandled Promise Rejection:"
   {
      [functions]: ,
      __proto__: { },
      description: "Määrittämättömän tai tyhjän viittauksen ominaisuutta textContent ei voi noutaa",
      message: "Määrittämättömän tai tyhjän viittauksen ominaisuutta textContent ei voi noutaa",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Määrittämättömän tai tyhjän viittauksen ominaisuutta textContent ei voi noutaa
   at value (http://none/1/mod_hvp/cachedassets/eaeb60ee776fdab3d69bafa6f9955367b362c894.js:3614:9795)
   at value (http://none/1/mod_hvp/cachedassets/eaeb60ee776fdab3d69bafa6f9955367b362c894.js:3614:9691)
   at Anonymous function (http://none/1/mod_hvp/cachedassets/eaeb60ee776fdab3d69bafa6f9955367b362c894.js:3614:14680)
   at f (http://none/1/mod_hvp/cachedassets/eaeb60ee776fdab3d69bafa6f9955367b362c894.js:3614:14627)
   at Anonymous function (http://none/1/mod_hvp/cachedassets/eaeb60ee776fdab3d69bafa6f9955367b362c894.js:3614:28965)
   at Anonymous function (http://none/1/mod_hvp/cachedassets/eaeb60ee776fdab3d69bafa6f9955367b362c894.js:3614:1634)"
   }`

**Comment by Urpokarhu1** [comment]
Hello,

This issues is already located at:

https://github.com/otacke/h5p-agamotto/issues/49

**Comment by thomasmars** [comment]
My bad :) reopening

**Comment by otacke** [comment]
This should have been fixed and should be working in the latest master version that's pending for review in [HFP-2770](https://h5ptechnology.atlassian.net/browse/HFP-2770).

**Comment by thomasmars** [comment]
@fnoks

**Comment by otacke** [comment]
Has been released on h5p.org now.
